tstitle: Farmaan Syed - AI Engineer / Data Scientist
description: Early-career professional passionate about AI and data science.
baseurl: ""
url: "https://farmaan10.github.io"

theme: minima

header_pages:
  - about.md
  - experience.md
  - projects.md
  - other-experiences.md

minima:
  social_links:
    github: Farmaan10
    linkedin: farmaan-syed-21a27617b/
